# Makefile for mmc
# written by hyan23
# Date: 2018.05.03

OBJECTS		=		mmc.o \
					mapper0.o mapper1.o mapper2.o mapper3.o \
					mapper4.o mapper7.o mapper9.o mapper10.o
TARGET		=		mmc.a

include ../../include/Makefile